In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the Dataset
df = pd.read_csv("Mobiles_Dataset.csv")
df

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,"1,005 Ratings",41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,"1,005 Ratings",41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,"₹1,499",₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
980,Kechaoda A27,"₹1,499",₹975,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
981,Kechaoda A27,"₹1,499",₹975,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982,Kechaoda A27,"₹1,499",₹930,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983,Kechaoda A27,"₹1,499",₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [3]:
# seeing how many rows and columns
df.shape

(984, 12)

In [4]:
# observing the information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         984 non-null    object
 1   Actual price         984 non-null    object
 2   Discount price       984 non-null    object
 3   Stars                984 non-null    float64
 4   Rating               984 non-null    object
 5   Reviews              984 non-null    object
 6   RAM (GB)             984 non-null    object
 7   Storage (GB)         984 non-null    object
 8   Display Size (inch)  984 non-null    float64
 9   Camera               908 non-null    object
 10  Description          984 non-null    object
 11  Link                 984 non-null    object
dtypes: float64(2), object(10)
memory usage: 92.4+ KB

In [5]:
# checking for the missing value 
df.isnull().sum()

Product Name            0
Actual price            0
Discount price          0
Stars                   0
Rating                  0
Reviews                 0
RAM (GB)                0
Storage (GB)            0
Display Size (inch)     0
Camera                 76
Description             0
Link                    0
dtype: int64

In [6]:
    # checking for the dupliacted rows
    df.duplicated().sum()

0

In [7]:
# seeing the columns name 
df.columns

Index(['Product Name', 'Actual price', 'Discount price', 'Stars', 'Rating',
       'Reviews', 'RAM (GB)', 'Storage (GB)', 'Display Size (inch)', 'Camera',
       'Description', 'Link'],
      dtype='object')

In [8]:
# countin the unique product names 
df['Product Name'].nunique()

657

In [9]:
# dropping the duplicated records in product Name 
df = df.drop_duplicates(subset="Product Name")

In [10]:
# after dropping the duplicated records 
df

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,"1,005 Ratings",41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,"1,005 Ratings",41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
971,Kechaoda K33,"₹1,412","₹1,064",4.0,"9,879 Ratings",597 Reviews,NIL,NIL,1.40,3MP + 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB3...,https://www.flipkart.com/kechaoda-k33/p/itmfgp...
973,Kechaoda K28,"₹1,399","₹1,260",4.0,"4,073 Ratings",323 Reviews,NIL,NIL,2.40,3MP,32 MB RAM | 64 MB ROM | Expandable Upto 16 GB6...,https://www.flipkart.com/kechaoda-k28/p/itmf3p...
974,LAVA A3 vibe,"₹1,319","₹1,212",4.2,"21,425 Ratings","2,247 Reviews",NIL,0,1.77,3MP,0 GB ROM | Expandable Upto 32 GB4.5 cm (1.77 i...,https://www.flipkart.com/lava-a3-vibe/p/itmed3...
975,Kechaoda A26,"₹1,499",₹930,4.0,"22,244 Ratings","1,377 Reviews",NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...
978,Kechaoda A27,"₹1,499",₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [11]:
# Removing the unwanted text from the ratings columns and also changing its data type to int
df["Rating"] = df["Rating"].str.replace(" Ratings", "").str.replace(",", "").astype("int")

C:\Users\thamb\AppData\Local\Temp\ipykernel_7188\646143331.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rating"] = df["Rating"].str.replace(" Ratings", "").str.replace(",", "").astype("int")

In [12]:
df

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,1005,41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,1005,41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
971,Kechaoda K33,"₹1,412","₹1,064",4.0,9879,597 Reviews,NIL,NIL,1.40,3MP + 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB3...,https://www.flipkart.com/kechaoda-k33/p/itmfgp...
973,Kechaoda K28,"₹1,399","₹1,260",4.0,4073,323 Reviews,NIL,NIL,2.40,3MP,32 MB RAM | 64 MB ROM | Expandable Upto 16 GB6...,https://www.flipkart.com/kechaoda-k28/p/itmf3p...
974,LAVA A3 vibe,"₹1,319","₹1,212",4.2,21425,"2,247 Reviews",NIL,0,1.77,3MP,0 GB ROM | Expandable Upto 32 GB4.5 cm (1.77 i...,https://www.flipkart.com/lava-a3-vibe/p/itmed3...
975,Kechaoda A26,"₹1,499",₹930,4.0,22244,"1,377 Reviews",NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...
978,Kechaoda A27,"₹1,499",₹967,4.0,11022,693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [13]:
# Renmaed the columns from Reviwes to Overall Reviews
df = df.rename(columns={"Reviews":"Overall_Reviews"})

In [14]:
df

,Product Name,Actual price,Discount price,Stars,Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,44793,"2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,1005,41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,1005,41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
971,Kechaoda K33,"₹1,412","₹1,064",4.0,9879,597 Reviews,NIL,NIL,1.40,3MP + 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB3...,https://www.flipkart.com/kechaoda-k33/p/itmfgp...
973,Kechaoda K28,"₹1,399","₹1,260",4.0,4073,323 Reviews,NIL,NIL,2.40,3MP,32 MB RAM | 64 MB ROM | Expandable Upto 16 GB6...,https://www.flipkart.com/kechaoda-k28/p/itmf3p...
974,LAVA A3 vibe,"₹1,319","₹1,212",4.2,21425,"2,247 Reviews",NIL,0,1.77,3MP,0 GB ROM | Expandable Upto 32 GB4.5 cm (1.77 i...,https://www.flipkart.com/lava-a3-vibe/p/itmed3...
975,Kechaoda A26,"₹1,499",₹930,4.0,22244,"1,377 Reviews",NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...
978,Kechaoda A27,"₹1,499",₹967,4.0,11022,693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [15]:
# Removing the unwanted text from the overall reviews columns and also changing its data type to int
df["Overall_Reviews"]=df["Overall_Reviews"].str.replace("Reviews","").str.replace(",", "").astype("int")

In [16]:
df

,Product Name,Actual price,Discount price,Stars,Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
971,Kechaoda K33,"₹1,412","₹1,064",4.0,9879,597,NIL,NIL,1.40,3MP + 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB3...,https://www.flipkart.com/kechaoda-k33/p/itmfgp...
973,Kechaoda K28,"₹1,399","₹1,260",4.0,4073,323,NIL,NIL,2.40,3MP,32 MB RAM | 64 MB ROM | Expandable Upto 16 GB6...,https://www.flipkart.com/kechaoda-k28/p/itmf3p...
974,LAVA A3 vibe,"₹1,319","₹1,212",4.2,21425,2247,NIL,0,1.77,3MP,0 GB ROM | Expandable Upto 32 GB4.5 cm (1.77 i...,https://www.flipkart.com/lava-a3-vibe/p/itmed3...
975,Kechaoda A26,"₹1,499",₹930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...
978,Kechaoda A27,"₹1,499",₹967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [17]:
# After that checking the data type which we have changed 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 657 entries, 0 to 978
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         657 non-null    object
 1   Actual price         657 non-null    object
 2   Discount price       657 non-null    object
 3   Stars                657 non-null    float64
 4   Rating               657 non-null    int32
 5   Overall_Reviews      657 non-null    int32
 6   RAM (GB)             657 non-null    object
 7   Storage (GB)         657 non-null    object
 8   Display Size (inch)  657 non-null    float64
 9   Camera               609 non-null    object
 10  Description          657 non-null    object
 11  Link                 657 non-null    object
dtypes: float64(2), int32(2), object(8)
memory usage: 61.6+ KB

In [18]:
# Removing the unwanted text from tha Actual Price Columns 
df["Actual price"] = pd.to_numeric(df["Actual price"].str.replace("₹", "").str.replace(",", ""), errors='coerce')

In [19]:
# Filling the Missing values as 0.0
df["Actual price"] =df["Actual price"] .fillna(0.0)

In [20]:
# Converting the data type to int
df["Actual price"]  = df["Actual price"].astype("int")

In [21]:
# Removing the unwanted text from tha Discount Price Columns 
df["Discount price"] = pd.to_numeric(df["Discount price"].str.replace("₹", "").str.replace(",", ""), errors='coerce')

In [22]:
# Filling the Missing values as 0.0
df["Discount price"] = df["Discount price"].fillna(0.0)

In [23]:
# Converting the data type to int
df["Discount price"] = df["Discount price"].astype("int")

In [24]:
# After that checking the data type which we have changed 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 657 entries, 0 to 978
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         657 non-null    object
 1   Actual price         657 non-null    int32
 2   Discount price       657 non-null    int32
 3   Stars                657 non-null    float64
 4   Rating               657 non-null    int32
 5   Overall_Reviews      657 non-null    int32
 6   RAM (GB)             657 non-null    object
 7   Storage (GB)         657 non-null    object
 8   Display Size (inch)  657 non-null    float64
 9   Camera               609 non-null    object
 10  Description          657 non-null    object
 11  Link                 657 non-null    object
dtypes: float64(2), int32(4), object(6)
memory usage: 56.5+ KB

In [25]:
# Renamed the columns starts to starts(out of 5)
df.rename(columns={"Stars":"Stars(out of 5)"},inplace = True)

In [26]:
# Dropped the columns Link ans Description because i dont think that the columns gives any information
df.drop(columns=["Link","Description"],inplace = True)

In [27]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
971,Kechaoda K33,1412,1064,4.0,9879,597,NIL,NIL,1.40,3MP + 0MP
973,Kechaoda K28,1399,1260,4.0,4073,323,NIL,NIL,2.40,3MP
974,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP
975,Kechaoda A26,1499,930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP
978,Kechaoda A27,1499,967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP

In [28]:
# Changed the index 
df = df.reset_index(drop=True)

In [29]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
652,Kechaoda K33,1412,1064,4.0,9879,597,NIL,NIL,1.40,3MP + 0MP
653,Kechaoda K28,1399,1260,4.0,4073,323,NIL,NIL,2.40,3MP
654,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP
655,Kechaoda A26,1499,930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP
656,Kechaoda A27,1499,967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP

In [30]:
# Now checking the columns of RAM which have NIL values 
df[df["RAM (GB)"]=="NIL"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
17,"itel it5027 6.1cm Screen,1200mAh Battery Wirel...",1499,1177,3.8,466,30,NIL,NIL,2.40,3MP + 0MP
19,Nokia 105,1699,1399,3.4,753,37,NIL,NIL,1.77,0MP | 0MP
...,...,...,...,...,...,...,...,...,...,...
652,Kechaoda K33,1412,1064,4.0,9879,597,NIL,NIL,1.40,3MP + 0MP
653,Kechaoda K28,1399,1260,4.0,4073,323,NIL,NIL,2.40,3MP
654,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP
655,Kechaoda A26,1499,930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP
656,Kechaoda A27,1499,967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP

# Replaced the NIL values to its original Values

In [31]:
# Now replacing the values of Apple iphone 12 
df[df["Product Name"].str.startswith("Apple iPhone 12")].index.to_list()

[649, 650, 651]

In [32]:
df.iloc[[649,650,651],6] = 4

In [33]:
df[df["Product Name"].str.startswith("Apple iPhone 13")].index.to_list()

[637, 643, 644, 645, 646]

In [34]:
df.iloc[[637, 643, 644, 645, 646],6] = 4

In [35]:
df.iloc[596,6] = 0

In [36]:
df[df["Product Name"].str.startswith("Apple iPhone 14 Plus")].index.to_list()

[117, 311, 510, 511, 542, 543]

In [37]:
df.iloc[[117, 311, 510, 511, 542, 543],6] = 6

In [38]:
df[df["Product Name"].str.startswith("Apple iPhone 15 Plus")].index.to_list()

[21, 509, 562, 573, 623]

In [39]:
df.iloc[[21, 509, 562, 573, 623],6] = 6

In [40]:
df[df["RAM (GB)"]=="NIL"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.10,48MP + 12MP
17,"itel it5027 6.1cm Screen,1200mAh Battery Wirel...",1499,1177,3.8,466,30,NIL,NIL,2.40,3MP + 0MP
19,Nokia 105,1699,1399,3.4,753,37,NIL,NIL,1.77,0MP | 0MP
...,...,...,...,...,...,...,...,...,...,...
652,Kechaoda K33,1412,1064,4.0,9879,597,NIL,NIL,1.40,3MP + 0MP
653,Kechaoda K28,1399,1260,4.0,4073,323,NIL,NIL,2.40,3MP
654,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP
655,Kechaoda A26,1499,930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP
656,Kechaoda A27,1499,967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP

In [41]:
df1 = df[df["Product Name"].str.startswith("Apple iPhone 15")]
df1

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.1,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.1,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.1,48MP + 12MP
21,"Apple iPhone 15 Plus (Yellow, 128 GB)",89600,73999,4.6,7658,637,6,128,6.7,48MP + 12MP
338,"Apple iPhone 15 (Green, 256 GB)",89600,75999,4.6,44793,2402,NIL,256,6.1,48MP + 12MP
396,"Apple iPhone 15 (Black, 256 GB)",89600,75999,4.6,44793,2402,NIL,256,6.1,48MP + 12MP
397,"Apple iPhone 15 (Black, 512 GB)",109600,95999,4.6,44793,2402,NIL,512,6.1,48MP + 12MP
435,"Apple iPhone 15 (Yellow, 128 GB)",79600,65999,4.6,44793,2402,NIL,128,6.1,48MP + 12MP
509,"Apple iPhone 15 Plus (Pink, 128 GB)",89600,73999,4.6,7658,637,6,128,6.7,48MP + 12MP
540,"Apple iPhone 15 (Pink, 128 GB)",79600,66499,4.6,44793,2402,NIL,128,6.1,48MP + 12MP
562,"Apple iPhone 15 Plus (Black, 128 GB)",89600,73999,4.6,7658,637,6,128,6.7,48MP + 12MP
573,"Apple iPhone 15 Plus (Green, 128 GB)",89600,73999,4.6,7658,637,6,128,6.7,48MP + 12MP
623,"Apple iPhone 15 Plus (Blue, 128 GB)",89600,73999,4.6,7658,637,6,128,6.7,48MP + 12MP

In [42]:
df1[df1["RAM (GB)"]=="NIL"].index.to_list()

[0, 1, 2, 338, 396, 397, 435, 540]

In [43]:
df.iloc[[0, 1, 2, 338, 396, 397, 435, 540],6] = 4

In [44]:
df[df["RAM (GB)"]=="NIL"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
17,"itel it5027 6.1cm Screen,1200mAh Battery Wirel...",1499,1177,3.8,466,30,NIL,NIL,2.40,3MP + 0MP
19,Nokia 105,1699,1399,3.4,753,37,NIL,NIL,1.77,0MP | 0MP
27,LAVA A3 Vibe DS Keypad Mobile| 1750 mAh Batter...,1649,1208,4.1,1536,97,NIL,NIL,1.77,3MP
44,LAVA A1 Josh BOL Keypad Mobile|1000 mAh Batter...,1399,960,4.0,7129,323,NIL,NIL,1.77,NaN
57,"Nokia 105 Single SIM, Keypad Mobile Phone with...",1599,1449,4.1,107686,6681,NIL,NIL,1.77,NaN
...,...,...,...,...,...,...,...,...,...,...
652,Kechaoda K33,1412,1064,4.0,9879,597,NIL,NIL,1.40,3MP + 0MP
653,Kechaoda K28,1399,1260,4.0,4073,323,NIL,NIL,2.40,3MP
654,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP
655,Kechaoda A26,1499,930,4.0,22244,1377,NIL,NIL,0.66,0MP | 0MP
656,Kechaoda A27,1499,967,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP

In [45]:
df[(df["RAM (GB)"]=="NIL") & (df["Storage (GB)"]=="NIL")].index.to_list()

[17,
 19,
 27,
 44,
 57,
 58,
 67,
 69,
 92,
 104,
 105,
 124,
 148,
 151,
 165,
 171,
 199,
 208,
 211,
 222,
 224,
 226,
 236,
 243,
 245,
 249,
 267,
 269,
 274,
 321,
 322,
 341,
 347,
 357,
 428,
 442,
 466,
 488,
 502,
 504,
 512,
 533,
 556,
 591,
 634,
 635,
 638,
 639,
 642,
 652,
 653,
 655,
 656]

In [46]:
# Dropped the columns which dont have the record for the RAM and Storage
df.drop(index=[17,19,27,44,57,58,67,69,92,104,105,124,148,151,165,171,199,208,211,222,224,
 226,
 236,
 243,
 245,
 249,
 267,
 269,
 274,
 321,
 322,
 341,
 347,
 357,
 428,
 442,
 466,
 488,
 502,
 504,
 512,
 533,
 556,
 591,
 634,
 635,
 638,
 639,
 642,
 652,
 653,
 655,
 656],inplace = True)

In [47]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
648,"Motorola G60 (Frosted Champagne, 128 GB)",21999,14999,4.1,78515,7700,6,128,6.78,108MP + 8MP
649,"Apple iPhone 12 (Blue, 128 GB)",54900,44999,4.6,210470,13889,4,128,6.10,12MP + 12MP
650,"Apple iPhone 12 (Black, 64 GB)",49900,38999,4.6,210470,13889,4,64,6.10,12MP + 12MP
651,"Apple iPhone 12 (Black, 256 GB)",64900,52999,4.6,210470,13889,4,256,6.10,12MP + 12MP
654,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP

In [48]:
df.reset_index(drop = True,inplace = True)

In [49]:
df[df["RAM (GB)"]=="NIL"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
59,LAVA Hero Shakti Keypad Mobile|1.8 inch Big Di...,1199,896,4.5,35,1,NIL,32,1.80,NaN
73,Kechaoda K115,1499,1060,4.1,35912,2497,NIL,32,1.44,3MP + 0MP
136,Kechaoda A26_black,1499,999,4.0,484,17,NIL,16,0.66,0MP | 0MP
139,itel ACE 2,1199,899,3.8,26,1,NIL,32,1.80,3MP + 0MP
170,"Apple iPhone 14 ((PRODUCT)RED, 128 GB)",69600,59999,4.6,299906,11619,NIL,128,6.10,12MP + 12MP
267,"Apple iPhone 14 (Starlight, 128 GB)",69600,59999,4.6,299906,11619,NIL,128,6.10,12MP + 12MP
293,MOTOROLA A50V Dual Sim Keypad Phone|1750 mAh B...,1699,1429,4.2,12,0,NIL,5,1.80,NaN
343,Jio PRIMA 4G,3499,3490,3.9,1012,55,NIL,4,2.40,3MP
427,MOTOROLA A10V DS Keypad Phone with Voice Featu...,1549,1279,4.1,1076,72,NIL,3,1.80,NaN
474,"Apple iPhone 14 (Purple, 128 GB)",69600,59999,4.6,299906,11619,NIL,128,6.10,12MP + 12MP
513,"Apple iPhone 14 (Midnight, 128 GB)",69600,59999,4.6,299906,11619,NIL,128,6.10,12MP + 12MP
567,"Apple iPhone 14 (Blue, 128 GB)",69600,59999,4.6,299906,11619,NIL,128,6.10,12MP + 12MP
603,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP

In [50]:
df.iloc[[170,267,474,513,567],6] = 4

In [51]:
df[df["RAM (GB)"]=="NIL"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
59,LAVA Hero Shakti Keypad Mobile|1.8 inch Big Di...,1199,896,4.5,35,1,NIL,32,1.80,NaN
73,Kechaoda K115,1499,1060,4.1,35912,2497,NIL,32,1.44,3MP + 0MP
136,Kechaoda A26_black,1499,999,4.0,484,17,NIL,16,0.66,0MP | 0MP
139,itel ACE 2,1199,899,3.8,26,1,NIL,32,1.80,3MP + 0MP
293,MOTOROLA A50V Dual Sim Keypad Phone|1750 mAh B...,1699,1429,4.2,12,0,NIL,5,1.80,NaN
343,Jio PRIMA 4G,3499,3490,3.9,1012,55,NIL,4,2.40,3MP
427,MOTOROLA A10V DS Keypad Phone with Voice Featu...,1549,1279,4.1,1076,72,NIL,3,1.80,NaN
603,LAVA A3 vibe,1319,1212,4.2,21425,2247,NIL,0,1.77,3MP

In [52]:
df.iloc[[59,73,136,139,293,343,427,603],6] = 0

In [53]:
df[df["RAM (GB)"]=='46875']

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
503,Nokia 2660 Flip 4G Volte Red keypad Mobile wit...,5899,5049,4.0,468,23,46875,125,2.8,3MP

In [54]:
df.iloc[503,6] = 0

In [55]:
df["RAM (GB)"].unique()

array([4, '4', '8', '6', '12', '16', '3', 6, '2', 0, '32'], dtype=object)

In [56]:
df["RAM (GB)"] = df["RAM (GB)"].astype("int")

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         604 non-null    object
 1   Actual price         604 non-null    int32
 2   Discount price       604 non-null    int32
 3   Stars(out of 5)      604 non-null    float64
 4   Rating               604 non-null    int32
 5   Overall_Reviews      604 non-null    int32
 6   RAM (GB)             604 non-null    int32
 7   Storage (GB)         604 non-null    object
 8   Display Size (inch)  604 non-null    float64
 9   Camera               568 non-null    object
dtypes: float64(2), int32(5), object(3)
memory usage: 35.5+ KB

In [58]:
# Checking the unique values of camera 
df["Camera"].unique()

array(['48MP + 12MP', '50MP ', '50MP + 2MP', '64MP + 8MP', '50MP + 8MP',
       '8MP | 16MP  ', '16MP ', '50MP | 32MP  ', '64MP ', nan, '13MP ',
       '50MP + 12MP', '200MP + 50MP', '8MP | 20MP  ', '50MP + 50MP',
       '3MP | 2MP  ', '32MP ', '64MP + 2MP', '108MP ', '8MP + 2MP',
       '08MP | 16MP  ', '50MP + 10MP', '08MP | 5MP  ', '8MP ',
       '3MP + 0MP', '13MP + 2MP', '200MP ', '8MP | 5MP  ',
       '13MP | 13MP  ', '2MP + 2MP', '12MP + 12MP', '2MP | 16MP  ',
       '50MP + 48MP', '0MP | 0MP  ', '50MP + 13MP', '50MP + 5MP',
       '64MP + 13MP', '108MP + 2MP', '200MP + 10MP', '48MP + 8MP',
       '32MP + 2MP', '48MP ', '2MP | 8MP  ', '3MP ', '08MP | 8MP  ',
       '108MP + 5MP', '13MP + 13MP', '108MP + 8MP', '50MP + 64MP',
       '5MP + 0MP', '48MP + 5MP'], dtype=object)

In [59]:
# Replacing the string "|" to "+"
df["Camera"] = df["Camera"].str.replace("|","+")

In [60]:
# Filling the missing values with 0MP
df["Camera"].fillna("0MP",inplace = True)

C:\Users\thamb\AppData\Local\Temp\ipykernel_7188\3409199643.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Camera"].fillna("0MP",inplace = True)

In [61]:
# Checking the values which have 0MP
df[df["Camera"]=="0MP"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
18,"Infinix SMART 8 HD (Shiny Gold, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.60,0MP
51,"Infinix SMART 8 (Rainbow Blue, 64 GB)",8999,7299,4.3,22640,1413,4,64,6.60,0MP
52,"Infinix SMART 8 (Rainbow Blue, 128 GB)",10999,7999,4.3,7947,469,8,128,6.60,0MP
59,LAVA Hero Shakti Keypad Mobile|1.8 inch Big Di...,1199,896,4.5,35,1,0,32,1.80,0MP
61,"Infinix HOT 30i (Glacier Blue, 128 GB)",0,11999,4.3,152825,8396,8,128,6.60,0MP
63,"Infinix HOT 40i (Starlit Black, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
183,"Infinix HOT 40i (Horizon Gold, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
193,"Infinix SMART 8 HD (Crystal Green, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.60,0MP
293,MOTOROLA A50V Dual Sim Keypad Phone|1750 mAh B...,1699,1429,4.2,12,0,0,5,1.80,0MP
322,"Infinix SMART 8 (Shiny Gold, 64 GB)",8999,7299,4.3,22640,1413,4,64,6.60,0MP
323,"Infinix SMART 8 (Shiny Gold, 128 GB)",10999,7999,4.3,7947,469,8,128,6.60,0MP
324,"Infinix SMART 8 HD (Timber Black, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.60,0MP
325,"Infinix HOT 30 5G (Knight Black, 128 GB)",14999,12499,4.2,5382,479,4,128,6.78,0MP
397,"Infinix SMART 8 (Timber Black, 128 GB)",10999,7999,4.3,7947,469,8,128,6.60,0MP
398,"Infinix SMART 8 (Timber Black, 64 GB)",8999,7299,4.3,22640,1413,4,64,6.60,0MP
427,MOTOROLA A10V DS Keypad Phone with Voice Featu...,1549,1279,4.1,1076,72,0,3,1.80,0MP
434,"Infinix HOT 30i (Marigold, 128 GB)",11999,9499,4.3,152825,8396,8,128,6.60,0MP
435,"Infinix HOT 30i (Marigold, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.60,0MP
436,"Infinix SMART 8 (Galaxy White, 64 GB)",8999,7299,4.3,22640,1413,4,64,6.60,0MP
437,"Infinix SMART 8 (Galaxy White, 128 GB)",10999,7999,4.3,7947,469,8,128,6.60,0MP
453,"Infinix Smart 8 Plus (Shiny Gold, 128 GB)",9999,7799,4.3,5161,312,4,128,6.60,0MP
461,"Infinix Note 30 5G (Magic Black, 256 GB)",19999,15999,4.2,99416,10445,8,256,6.78,0MP
462,"Infinix Note 30 5G (Magic Black, 128 GB)",17999,14999,4.1,4464,456,4,128,6.78,0MP
472,"POCO C55 (Power Black, 128 GB)",13999,10999,4.2,140711,8378,6,128,6.71,0MP
490,"Infinix HOT 30 5G (Miami Orange, 128 GB)",16999,13499,4.2,30039,2570,8,128,6.78,0MP
494,"Infinix Note 30 5G (Interstellar Blue, 256 GB)",19999,15999,4.2,99416,10445,8,256,6.78,0MP
505,"Infinix HOT 40i (Starfall Green, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
509,"Infinix HOT 40i (Palm Blue, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
527,"Infinix Smart 8 Plus (Galaxy White, 128 GB)",9999,7799,4.3,5161,312,4,128,6.60,0MP
528,"Infinix Smart 8 Plus (Timber Black, 128 GB)",9999,7799,4.3,5161,312,4,128,6.60,0MP
552,LAVA Hero 600i Sapphire Blue,1199,839,4.0,1870,115,0,NIL,1.80,0MP
556,"Infinix HOT 30i (Mirror Black, 128 GB)",11999,9499,4.3,152825,8396,8,128,6.60,0MP
557,"Infinix HOT 30i (Mirror Black, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.60,0MP
580,"Infinix SMART 8 HD (Galaxy White, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.60,0MP
587,"Infinix HOT 30i (Diamond White, 128 GB)",11999,9499,4.3,152825,8396,8,128,6.60,0MP
588,"Infinix HOT 30i (Diamond White, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.60,0MP

In [62]:
df[df["Product Name"].str.startswith("Infinix SMART 8 HD")]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
18,"Infinix SMART 8 HD (Shiny Gold, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.6,0MP
193,"Infinix SMART 8 HD (Crystal Green, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.6,0MP
324,"Infinix SMART 8 HD (Timber Black, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.6,0MP
580,"Infinix SMART 8 HD (Galaxy White, 64 GB)",7999,6699,4.3,33838,2357,3,64,6.6,0MP

In [63]:
df.iloc[[18,193,324,580],9] = "13MP + AI Lens"

In [64]:
df3 = df[df["Product Name"].str.startswith("Infinix SMART 8")]

In [65]:
df3[df3["Camera"]=='0MP'].index

Index([51, 52, 322, 323, 397, 398, 436, 437], dtype='int64')

In [66]:
df.iloc[[51, 52, 322, 323, 397, 398, 436, 437],9] = "50MP + AI Lens"

In [67]:
df[df["Product Name"].str.startswith("Infinix Smart 8 Plus")].index

Index([453, 527, 528], dtype='int64')

In [68]:
df.iloc[[453, 527, 528],8] = [6.70,6.70,6.79]

In [69]:
df.iloc[[453, 527, 528],9] = "50MP + AI Lens"

In [70]:
df[df["Product Name"].str.startswith("Infinix HOT 30i")].index

Index([61, 434, 435, 556, 557, 587, 588], dtype='int64')

In [71]:
df.iloc[[61, 434, 435, 555, 556, 586, 587],9] = "50MP + AI Lens"

In [72]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
599,"Motorola G60 (Frosted Champagne, 128 GB)",21999,14999,4.1,78515,7700,6,128,6.78,108MP + 8MP
600,"Apple iPhone 12 (Blue, 128 GB)",54900,44999,4.6,210470,13889,4,128,6.10,12MP + 12MP
601,"Apple iPhone 12 (Black, 64 GB)",49900,38999,4.6,210470,13889,4,64,6.10,12MP + 12MP
602,"Apple iPhone 12 (Black, 256 GB)",64900,52999,4.6,210470,13889,4,256,6.10,12MP + 12MP
603,LAVA A3 vibe,1319,1212,4.2,21425,2247,0,0,1.77,3MP

In [73]:
df.iloc[[453, 527, 528],9]

453    50MP + AI Lens
527    50MP + AI Lens
528    50MP + AI Lens
Name: Camera, dtype: object

In [74]:
df[df["Camera"]=="0MP"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
59,LAVA Hero Shakti Keypad Mobile|1.8 inch Big Di...,1199,896,4.5,35,1,0,32,1.80,0MP
63,"Infinix HOT 40i (Starlit Black, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
183,"Infinix HOT 40i (Horizon Gold, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
293,MOTOROLA A50V Dual Sim Keypad Phone|1750 mAh B...,1699,1429,4.2,12,0,0,5,1.80,0MP
325,"Infinix HOT 30 5G (Knight Black, 128 GB)",14999,12499,4.2,5382,479,4,128,6.78,0MP
427,MOTOROLA A10V DS Keypad Phone with Voice Featu...,1549,1279,4.1,1076,72,0,3,1.80,0MP
461,"Infinix Note 30 5G (Magic Black, 256 GB)",19999,15999,4.2,99416,10445,8,256,6.78,0MP
462,"Infinix Note 30 5G (Magic Black, 128 GB)",17999,14999,4.1,4464,456,4,128,6.78,0MP
472,"POCO C55 (Power Black, 128 GB)",13999,10999,4.2,140711,8378,6,128,6.71,0MP
490,"Infinix HOT 30 5G (Miami Orange, 128 GB)",16999,13499,4.2,30039,2570,8,128,6.78,0MP
494,"Infinix Note 30 5G (Interstellar Blue, 256 GB)",19999,15999,4.2,99416,10445,8,256,6.78,0MP
505,"Infinix HOT 40i (Starfall Green, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
509,"Infinix HOT 40i (Palm Blue, 256 GB)",10999,8999,4.1,12423,757,8,256,6.60,0MP
552,LAVA Hero 600i Sapphire Blue,1199,839,4.0,1870,115,0,NIL,1.80,0MP
557,"Infinix HOT 30i (Mirror Black, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.60,0MP
588,"Infinix HOT 30i (Diamond White, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.60,0MP

In [75]:
df[df["Product Name"].str.startswith("Infinix HOT 30i")].index

Index([61, 434, 435, 556, 557, 587, 588], dtype='int64')

In [76]:
df.iloc[[61, 434, 435, 555, 556, 586, 587],9] = "50MP + AI Lens"

In [77]:
df[df["Product Name"].str.startswith("Infinix HOT 40i")].index

Index([63, 183, 505, 509], dtype='int64')

In [78]:
df.iloc[[63, 183, 505, 509],9] = "50MP + AI Lens"

In [79]:
df[df["Product Name"].str.startswith("Infinix Note 30 5G")].index

Index([461, 462, 494], dtype='int64')

In [80]:
df.iloc[[461, 462, 494],9] = "108MP + 2MP + AI Lens"

In [81]:
df[df["Product Name"].str.startswith("Infinix HOT 30 5G")].index

Index([325, 490], dtype='int64')

In [82]:
df.iloc[[325, 490],9] = "50MP + AI Lens"

In [83]:
df.iloc[472,8] = 6.6

In [84]:
df.iloc[472,9] = "50MP"

In [85]:
df[df["Camera"]=="0MP"]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
59,LAVA Hero Shakti Keypad Mobile|1.8 inch Big Di...,1199,896,4.5,35,1,0,32,1.8,0MP
293,MOTOROLA A50V Dual Sim Keypad Phone|1750 mAh B...,1699,1429,4.2,12,0,0,5,1.8,0MP
427,MOTOROLA A10V DS Keypad Phone with Voice Featu...,1549,1279,4.1,1076,72,0,3,1.8,0MP
552,LAVA Hero 600i Sapphire Blue,1199,839,4.0,1870,115,0,NIL,1.8,0MP
557,"Infinix HOT 30i (Mirror Black, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.6,0MP
588,"Infinix HOT 30i (Diamond White, 64 GB)",9999,8399,4.2,28735,1597,4,64,6.6,0MP

In [86]:
df.iloc[[557,588],9] = "50MP" + "AI Lens"

In [87]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
599,"Motorola G60 (Frosted Champagne, 128 GB)",21999,14999,4.1,78515,7700,6,128,6.78,108MP + 8MP
600,"Apple iPhone 12 (Blue, 128 GB)",54900,44999,4.6,210470,13889,4,128,6.10,12MP + 12MP
601,"Apple iPhone 12 (Black, 64 GB)",49900,38999,4.6,210470,13889,4,64,6.10,12MP + 12MP
602,"Apple iPhone 12 (Black, 256 GB)",64900,52999,4.6,210470,13889,4,256,6.10,12MP + 12MP
603,LAVA A3 vibe,1319,1212,4.2,21425,2247,0,0,1.77,3MP

In [88]:
df[df["Actual price"]==0]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
42,"vivo Y200 Pro 5G (Silk Green, 128 GB)",0,24999,4.2,102,6,8,128,6.78,64MP + 2MP
61,"Infinix HOT 30i (Glacier Blue, 128 GB)",0,11999,4.3,152825,8396,8,128,6.60,50MP + AI Lens
83,"SAMSUNG Galaxy A55 5G (Awesome Navy, 256 GB)",0,48999,4.3,116,9,12,256,6.60,50MP + 12MP
104,"SAMSUNG Galaxy Z Fold6 5G (Silver Shadow, 256 GB)",0,164999,4.2,22,2,12,256,7.60,50MP + 12MP
105,"SAMSUNG Galaxy Z Fold6 5G (Silver Shadow, 512 GB)",0,176999,4.2,22,2,12,512,7.60,50MP + 12MP
111,"vivo V29 5G (Red, 128 GB)",0,32999,4.5,9299,1032,8,128,6.78,50MP + 8MP
117,"SAMSUNG Galaxy S24 5G (Onyx Black, 256 GB)",0,79999,4.5,1055,135,8,256,6.20,50MP + 10MP
121,"vivo V29 Pro 5G (Black, 256 GB)",0,39999,4.5,5966,905,8,256,6.78,50MP + 12MP
154,"Google Pixel 8a (Porcelain, 128 GB)",0,52999,4.1,866,102,8,128,6.10,64MP + 13MP
187,"SAMSUNG Galaxy S24 5G (Amber Yellow, 256 GB)",0,79999,4.5,1055,135,8,256,6.20,50MP + 10MP
189,"OnePlus 12R (Iron Gray, 128 GB)",0,39999,4.5,4278,292,8,128,6.78,50MP
228,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
229,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 256 GB)",0,36999,4.3,524,35,8,256,6.60,50MP + 8MP
234,"SAMSUNG Galaxy A35 5G (Awesome Lilac, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
266,LAVA Yuva 3 with Dual Sim|5000 mAh Battery|13M...,0,0,4.1,203,12,4,64,6.50,13MP
303,"OPPO Reno8T 5G (Sunrise Gold, 128 GB)",0,38999,4.3,17483,1462,8,128,6.70,108MP + 2MP
314,"SAMSUNG Galaxy S24 5G (Cobalt Violet, 512 GB)",0,89999,4.5,1055,135,8,512,6.20,50MP + 10MP
326,"vivo V29 5G (Blue, 256 GB)",0,36999,4.5,2883,287,12,256,6.78,50MP + 8MP
336,"SAMSUNG Galaxy Z Flip6 5G (Silver Shadow, 256 GB)",0,109999,5.0,8,0,12,256,6.70,50MP + 12MP
385,"vivo T2x 5G (Black Gladiator, 128 GB)",0,17999,4.4,180202,9268,4,128,6.58,50MP + 2MP
396,"SAMSUNG Galaxy Z Flip6 5G (Blue, 256 GB)",0,109999,5.0,8,0,12,256,6.70,50MP + 12MP
410,"Google Pixel 8a (Obsidian, 256 GB)",0,59999,4.1,866,102,8,256,6.10,64MP + 13MP
431,"SAMSUNG Galaxy Z Fold6 5G (Navy, 256 GB)",0,164999,4.2,22,2,12,256,7.60,50MP + 12MP
438,"OPPO Reno8T 5G (Midnight Black, 128 GB)",0,38999,4.3,17483,1462,8,128,6.70,108MP + 2MP
499,"SAMSUNG Galaxy A55 5G (Awesome Iceblue, 256 GB)",0,48999,4.3,116,9,12,256,6.60,50MP + 12MP
511,"SAMSUNG Galaxy A35 5G (Awesome Navy, 256 GB)",0,36999,4.3,524,35,8,256,6.60,50MP + 8MP
512,"SAMSUNG Galaxy A35 5G (Awesome Navy, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
520,"OPPO A77 (Sunset Orange, 128 GB)",0,19999,4.2,1238,75,4,128,6.56,50MP + 2MP
532,"OnePlus 11R 5G (Sonic Black, 256 GB)",0,44999,4.5,12951,871,16,256,6.70,50MP
549,"vivo V29 Pro 5G (Blue, 256 GB)",0,39999,4.5,5966,905,8,256,6.78,50MP + 12MP
550,"vivo V29 5G (Blue, 128 GB)",0,32999,4.5,9299,1032,8,128,6.78,50MP + 8MP
558,"SAMSUNG Galaxy S24+ 5G (Onyx Black, 256 GB)",0,99999,4.5,147,18,12,256,6.70,50MP + 10MP
563,"REDMI Note 13 5G (Stealth Black, 128 GB)",0,0,4.2,10801,650,6,128,6.67,108MP

In [89]:
df.iloc[[42,61,83,104,105,111,117,121,154],1] = [26999,13999,50999,167999,178999,34999,81999,47999,54999]

In [90]:
df[df["Actual price"]==0]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
187,"SAMSUNG Galaxy S24 5G (Amber Yellow, 256 GB)",0,79999,4.5,1055,135,8,256,6.20,50MP + 10MP
189,"OnePlus 12R (Iron Gray, 128 GB)",0,39999,4.5,4278,292,8,128,6.78,50MP
228,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
229,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 256 GB)",0,36999,4.3,524,35,8,256,6.60,50MP + 8MP
234,"SAMSUNG Galaxy A35 5G (Awesome Lilac, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
266,LAVA Yuva 3 with Dual Sim|5000 mAh Battery|13M...,0,0,4.1,203,12,4,64,6.50,13MP
303,"OPPO Reno8T 5G (Sunrise Gold, 128 GB)",0,38999,4.3,17483,1462,8,128,6.70,108MP + 2MP
314,"SAMSUNG Galaxy S24 5G (Cobalt Violet, 512 GB)",0,89999,4.5,1055,135,8,512,6.20,50MP + 10MP
326,"vivo V29 5G (Blue, 256 GB)",0,36999,4.5,2883,287,12,256,6.78,50MP + 8MP
336,"SAMSUNG Galaxy Z Flip6 5G (Silver Shadow, 256 GB)",0,109999,5.0,8,0,12,256,6.70,50MP + 12MP
385,"vivo T2x 5G (Black Gladiator, 128 GB)",0,17999,4.4,180202,9268,4,128,6.58,50MP + 2MP
396,"SAMSUNG Galaxy Z Flip6 5G (Blue, 256 GB)",0,109999,5.0,8,0,12,256,6.70,50MP + 12MP
410,"Google Pixel 8a (Obsidian, 256 GB)",0,59999,4.1,866,102,8,256,6.10,64MP + 13MP
431,"SAMSUNG Galaxy Z Fold6 5G (Navy, 256 GB)",0,164999,4.2,22,2,12,256,7.60,50MP + 12MP
438,"OPPO Reno8T 5G (Midnight Black, 128 GB)",0,38999,4.3,17483,1462,8,128,6.70,108MP + 2MP
499,"SAMSUNG Galaxy A55 5G (Awesome Iceblue, 256 GB)",0,48999,4.3,116,9,12,256,6.60,50MP + 12MP
511,"SAMSUNG Galaxy A35 5G (Awesome Navy, 256 GB)",0,36999,4.3,524,35,8,256,6.60,50MP + 8MP
512,"SAMSUNG Galaxy A35 5G (Awesome Navy, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
520,"OPPO A77 (Sunset Orange, 128 GB)",0,19999,4.2,1238,75,4,128,6.56,50MP + 2MP
532,"OnePlus 11R 5G (Sonic Black, 256 GB)",0,44999,4.5,12951,871,16,256,6.70,50MP
549,"vivo V29 Pro 5G (Blue, 256 GB)",0,39999,4.5,5966,905,8,256,6.78,50MP + 12MP
550,"vivo V29 5G (Blue, 128 GB)",0,32999,4.5,9299,1032,8,128,6.78,50MP + 8MP
558,"SAMSUNG Galaxy S24+ 5G (Onyx Black, 256 GB)",0,99999,4.5,147,18,12,256,6.70,50MP + 10MP
563,"REDMI Note 13 5G (Stealth Black, 128 GB)",0,0,4.2,10801,650,6,128,6.67,108MP

In [91]:
df.iloc[[187,189,228,229,234,266,303,314,326,336],1] = [81999,41999,35999,38999,35999,7465,41999,91999,38999,111999]

In [92]:
df[df["Actual price"]==0]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
385,"vivo T2x 5G (Black Gladiator, 128 GB)",0,17999,4.4,180202,9268,4,128,6.58,50MP + 2MP
396,"SAMSUNG Galaxy Z Flip6 5G (Blue, 256 GB)",0,109999,5.0,8,0,12,256,6.70,50MP + 12MP
410,"Google Pixel 8a (Obsidian, 256 GB)",0,59999,4.1,866,102,8,256,6.10,64MP + 13MP
431,"SAMSUNG Galaxy Z Fold6 5G (Navy, 256 GB)",0,164999,4.2,22,2,12,256,7.60,50MP + 12MP
438,"OPPO Reno8T 5G (Midnight Black, 128 GB)",0,38999,4.3,17483,1462,8,128,6.70,108MP + 2MP
499,"SAMSUNG Galaxy A55 5G (Awesome Iceblue, 256 GB)",0,48999,4.3,116,9,12,256,6.60,50MP + 12MP
511,"SAMSUNG Galaxy A35 5G (Awesome Navy, 256 GB)",0,36999,4.3,524,35,8,256,6.60,50MP + 8MP
512,"SAMSUNG Galaxy A35 5G (Awesome Navy, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
520,"OPPO A77 (Sunset Orange, 128 GB)",0,19999,4.2,1238,75,4,128,6.56,50MP + 2MP
532,"OnePlus 11R 5G (Sonic Black, 256 GB)",0,44999,4.5,12951,871,16,256,6.70,50MP
549,"vivo V29 Pro 5G (Blue, 256 GB)",0,39999,4.5,5966,905,8,256,6.78,50MP + 12MP
550,"vivo V29 5G (Blue, 128 GB)",0,32999,4.5,9299,1032,8,128,6.78,50MP + 8MP
558,"SAMSUNG Galaxy S24+ 5G (Onyx Black, 256 GB)",0,99999,4.5,147,18,12,256,6.70,50MP + 10MP
563,"REDMI Note 13 5G (Stealth Black, 128 GB)",0,0,4.2,10801,650,6,128,6.67,108MP

In [93]:
df.iloc[266,2] = 7999

In [94]:
df.iloc[[385,396,410,431,438,499,511],1] = [20999,111999,61999,166999,40999,51999,38999]

In [95]:
df[df["Actual price"]==0]

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
512,"SAMSUNG Galaxy A35 5G (Awesome Navy, 128 GB)",0,33999,4.3,524,35,8,128,6.60,50MP + 8MP
520,"OPPO A77 (Sunset Orange, 128 GB)",0,19999,4.2,1238,75,4,128,6.56,50MP + 2MP
532,"OnePlus 11R 5G (Sonic Black, 256 GB)",0,44999,4.5,12951,871,16,256,6.70,50MP
549,"vivo V29 Pro 5G (Blue, 256 GB)",0,39999,4.5,5966,905,8,256,6.78,50MP + 12MP
550,"vivo V29 5G (Blue, 128 GB)",0,32999,4.5,9299,1032,8,128,6.78,50MP + 8MP
558,"SAMSUNG Galaxy S24+ 5G (Onyx Black, 256 GB)",0,99999,4.5,147,18,12,256,6.70,50MP + 10MP
563,"REDMI Note 13 5G (Stealth Black, 128 GB)",0,0,4.2,10801,650,6,128,6.67,108MP

In [96]:
df.iloc[[512,520,532,549,550,558,563],1] = [35999,21999,46999,41999,35999,103999,20999]

In [97]:
df.iloc[563,2] = 15799

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         604 non-null    object
 1   Actual price         604 non-null    int32
 2   Discount price       604 non-null    int32
 3   Stars(out of 5)      604 non-null    float64
 4   Rating               604 non-null    int32
 5   Overall_Reviews      604 non-null    int32
 6   RAM (GB)             604 non-null    int32
 7   Storage (GB)         604 non-null    object
 8   Display Size (inch)  604 non-null    float64
 9   Camera               604 non-null    object
dtypes: float64(2), int32(5), object(3)
memory usage: 35.5+ KB

In [99]:
df.describe()

,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Display Size (inch)
count,604.000000,604.000000,604.000000,604.000000,604.000000,604.000000,604.000000
mean,31775.096026,25624.872517,4.291391,25099.998344,1606.958609,7.334437,6.539977
std,26772.960386,23169.821870,0.179530,54675.950390,3099.360210,3.151362,0.686278
min,1199.000000,839.000000,3.500000,4.000000,0.000000,0.000000,0.660000
25%,14499.000000,10989.500000,4.200000,889.250000,57.000000,4.000000,6.560000
50%,22999.000000,18249.000000,4.300000,5793.000000,410.000000,8.000000,6.670000
75%,37999.000000,31999.000000,4.400000,19849.000000,1433.250000,8.000000,6.740000
max,178999.000000,176999.000000,5.000000,429459.000000,23258.000000,32.000000,7.820000

In [100]:
df

,Product Name,Actual price,Discount price,Stars(out of 5),Rating,Overall_Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera
0,"Apple iPhone 15 (Green, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
1,"Apple iPhone 15 (Blue, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
2,"Apple iPhone 15 (Black, 128 GB)",79600,65999,4.6,44793,2402,4,128,6.10,48MP + 12MP
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999,11489,4.0,1005,41,4,128,6.56,50MP
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999,12999,4.0,1005,41,4,64,6.56,50MP
...,...,...,...,...,...,...,...,...,...,...
599,"Motorola G60 (Frosted Champagne, 128 GB)",21999,14999,4.1,78515,7700,6,128,6.78,108MP + 8MP
600,"Apple iPhone 12 (Blue, 128 GB)",54900,44999,4.6,210470,13889,4,128,6.10,12MP + 12MP
601,"Apple iPhone 12 (Black, 64 GB)",49900,38999,4.6,210470,13889,4,64,6.10,12MP + 12MP
602,"Apple iPhone 12 (Black, 256 GB)",64900,52999,4.6,210470,13889,4,256,6.10,12MP + 12MP
603,LAVA A3 vibe,1319,1212,4.2,21425,2247,0,0,1.77,3MP